/:
  controller: Security
  action: install

/404:
  controller: Main
  action: page404

/utilisateur:
  controller: User
  action: default

/ajout-d-un-utilisateur:
  controller: User
  action: add


/connexion:
  controller: User
  action: login

/afficher-un-utilisateur:
  controller: User
  action: show


/afficher-les-utilisateurs:
  controller: User
  action: showAll

/admin/liste-magasin:
  controller: Shop
  action: displayShop

/admin/reviews:
  controller: Reviews
  action: showReviews

/admin/dashboard:
  controller: Dashboard
  action: dashboard

/admin/nouveau-magasin:
  controller: Shop
  action: newShop

/admin/display-pages:
  controller: Pages
  action: show

/admin/publisher:
  controller: Publisher
  action: publisher

/admin/check-review:
  controller: Reviews
  action: checkReviews

/admin/nouvelle-page:
  controller: Pages
  action: newPage

/admin/modification-page:
  controller: Pages
  action: updatePage