/:
  controller: Security
  action: install

/404:
  controller: Main
  action: page404

/connexion:
  controller: User
  action: login

/connexion-admin:
  controller: User
  action: loginAdmin

/deconnexion:
  controller: Security
  action: logout

/admin/liste-magasin:
  controller: Shop
  action: displayShop

/admin/reviews:
  controller: Reviews
  action: showReviews

/admin/dashboard:
  controller: Dashboard
  action: dashboard

/admin/display-category:
  controller: Category
  action: show

/admin/nouvelle-categorie:
  controller: Category
  action: newCategory

/admin/modification-categorie:
  controller: Category
  action: updateCategory

/admin/suppression-categorie:
  controller : Category
  action: deleteCategory

/admin/nouveau-magasin:
  controller: Shop
  action: newShop

/admin/pages:
  controller: Pages
  action: pages

/admin/publisher:
  controller: Publisher
  action: publisher

/admin/check-review:
  controller: Reviews
  action: checkReviews

/admin/nouveau-role:
  controller: Role
  action: newRole

/admin/role:
  controller: Role
  action: showAll

/admin/modification-role:
  controller: Role
  action: updateRole

/admin/suppression-role:
  controller: Role
  action: deleteRole

/admin/info-reviews:
  controller: Reviews
  action: showProducts

/admin/del-review:
  controller: Reviews
  action: deleteReviews

/admin/show-reviews-from-products:
  controller: Reviews
  action: showReviewsFromProducts

/admin/ajout-client:
  controller: User
  action: newClient

/admin/liste-client:
  controller: User
  action: displayClient

/admin/modification-client:
  controller: User
  action: updateClient

/admin/suppression-client:
  controller: User
  action: deleteClient

/admin/detail-magasin:
  controller : Shop
  action : detailShop

/inscription:
  controller : User
  action: register

/mot-de-passe-oublie:
  controller : Security
  action : pwdPerdu

/recuperation-mot-de-passe:
  controller : Security
  action : recuperationpwd

/admin/delete-shop:
  controller: Shop
  action: deleteShop

/confirmation-inscription:
  controller: Security
  action: confirmedRegister

/admin/liste-utilisateurs:
  controller: User
  action: displayUsers

/admin/ajout-utilisateur:
  controller: User
  action: addUsers

/admin/suppression-utilisateur:
  controller: User
  action: deleteUser

/admin/modification-utilisateur:
  controller: User
  action: updateUser

/admin/utilisateur-changement-mdp:
  controller: User
  action : changeUserPwd

/admin/liste-commande:
  controller: Commande
  action: listeCommande

/admin/detail-commande:
  controller: Commande
  action: displayCommande
/collections:
  controller: Product
  action : displayProductsFront

/produit:
  controller: Product
  action: infoProductFront

/produit/prix:
  controller: Product
  action: getPrice

/panier:
  controller: ShoppingCart
  action : displayShoppingCart

/ajout-panier:
  controller : ShoppingCart
  action : addShoppingCart

/supprimer-panier:
  controller: ShoppingCart
  action: deleteShoppingCart

/admin/parametres:
  controller: Settings
  action : displaySettings

/admin/parametres-site:
  controller: Settings
  action : displaySettingsSite

/admin/update-settings:
  controller: Settings
  action : update

/admin/annuler-commande:
  controller: Commande
  action: cancelCommande
/admin/update-admin-email:
  controller: Settings
  action : updateAdminEmail

/admin/update-admin-password:
  controller: Settings
  action : updateAdminPassword

/admin/valider-commande:
  controller: Commande
  action: ValidCommande

/admin/terminer-commande:
  controller: Commande
  action: DoneCommande

/create-checkout-session:
  controller: Stripe
  action: paymentStripe

/paiement-stripe:
  controller: Stripe
  action: pagePaiementStripe

/success:
  controller: Stripe
  action: success

/cancel:
  controller: Stripe
  action: cancel
