/:
  controller: Security
  action: registerInstall

/404:
  controller: Main
  action: page404

/utilisateur:
  controller: User
  action: default

/ajout-d-un-utilisateur:
  controller: User
  action: add

/connexion:
  controller: User
  action: login

/connexion-admin:
  controller: User
  action: loginAdmin

/deconnexion:
  controller: Auth
  action: logout

/afficher-un-utilisateur:
  controller: User
  action: show

/afficher-les-utilisateurs:
  controller: User
  action: showAll

/admin/liste-magasin:
  controller: Shop
  action: displayShop

/admin/reviews:
  controller: Reviews
  action: showReviews

/admin/dashboard:
  controller: Dashboard
  action: dashboard

/admin/nouveau-magasin:
  controller: Shop
  action: newShop

/admin/pages:
  controller: Pages
  action: pages

/admin/publisher:
  controller: Publisher
  action: publisher

/admin/check-review:
  controller: Reviews
  action: checkReviews

/admin/nouveau-role:
  controller: Role
  action: newRole

/admin/role:
  controller: Role
  action: showAll

/admin/modification-role:
  controller: Role
  action: updateRole

/admin/suppression-role:
  controller: Role
  action: deleteRole

/admin/info-reviews:
  controller: Reviews
  action: showProducts

/admin/del-review:
  controller: Reviews
  action: deleteReviews

/admin/show-reviews-from-products:
  controller: Reviews
  action: showReviewsFromProducts

/admin/orders:
  controller: Orders
  action: showOrders

/admin/info-order:
  controller: Orders
  action: infoOrder

/admin/ajout-client:
  controller: User
  action: newClient

/admin/liste-client:
  controller: User
  action: displayClient

/admin/modification-client:
  controller: User
  action: updateClient

/admin/suppression-client:
  controller: User
  action: deleteClient

/admin/detail-magasin:
  controller : Shop
  action : detailShop

/inscription:
  controller : User
  action: register

/admin/liste-utilisateurs:
  controller: User
  action: displayUsers

/admin/ajout-utilisateur:
  controller: User
  action: addUsers

/admin/suppression-utilisateur:
  controller: User
  action: deleteUser

/admin/modification-utilisateur:
  controller: User
  action: updateUser

/admin/utilisateur-changement-mdp:
  controller: User
  action : changeUserPwd