/:
  controller: Security
  action: install

/404:
  controller: Main
  action: page404

/utilisateur:
  controller: User
  action: default

/ajout-d-un-utilisateur:
  controller: User
  action: add


/connexion:
  controller: User
  action: login

/connexion-admin:
  controller: User
  action: loginAdmin

/deconnexion:
  controller: Auth
  action: logout

/afficher-un-utilisateur:
  controller: User
  action: show


/afficher-les-utilisateurs:
  controller: User
  action: showAll

/admin/liste-magasin:
  controller: Shop
  action: displayShop

/admin/reviews:
  controller: Reviews
  action: showReviews

/admin/dashboard:
  controller: Dashboard
  action: dashboard

/admin/nouveau-magasin:
  controller: Shop
  action: newShop

/admin/pages:
  controller: Pages
  action: pages

/admin/publisher:
  controller: Publisher
  action: publisher

/admin/check-review:
  controller: Reviews
  action: checkReviews


/admin/info-reviews:
  controller: Reviews
  action: showProducts

/admin/del-review:
  controller: Reviews
  action: deleteReviews

/admin/show-reviews-from-products:
  controller: Reviews
  action: showReviewsFromProducts

/admin/orders:
  controller: Orders
  action: showOrders

/admin/info-order:
  controller: Orders
  action: infoOrder


/admin/ajout-client:
  controller: User
  action: newClient

/admin/liste-client:
  controller: User
  action: displayClient

/admin/modification-client:
  controller: User
  action: updateClient

/admin/suppression-client:
  controller: User
  action: deleteClient

/admin/detail-magasin:
  controller : Shop
  action : detailShop

/inscription:
  controller : User
  action: register


