/:
  controller: Installation
  action: install

/404:
  controller: Main
  action: page404

/utilisateur:
  controller: User
  action: default

/ajout-d-un-utilisateur:
  controller: User
  action: add


/s-inscrire:
  controller: User
  action: register

/afficher-un-utilisateur:
  controller: User
  action: show


/afficher-les-utilisateurs:
  controller: User
  action: showAll

/admin/liste-magasin:
  controller: Shop
  action: displayShop

/admin/reviews:
  controller: Reviews
  action: showReviews

/admin/dashboard:
  controller: Dashboard
  action: dashboard

/admin/nouveau-magasin:
  controller: Shop
  action: newShop

/admin/pages:
  controller: Pages
  action: pages

/start-install:
  controller: Installation
  action: startInstall