/:
  controller: Security
  action: install

/404:
  controller: Main
  action: page404

/utilisateur:
  controller: User
  action: default

/ajout-d-un-utilisateur:
  controller: User
  action: add

/connexion:
  controller: User
  action: login

/connexion-admin:
  controller: User
  action: loginAdmin

/deconnexion:
  controller: Security
  action: logout

/afficher-un-utilisateur:
  controller: User
  action: show

/afficher-les-utilisateurs:
  controller: User
  action: showAll

/admin/liste-magasin:
  controller: Shop
  action: displayShop

/admin/reviews:
  controller: Reviews
  action: showReviews

/admin/dashboard:
  controller: Dashboard
  action: dashboard


/admin/display-category:
  controller: Category
  action: show

/admin/nouvelle-categorie:
  controller: Category
  action: newCategory

/admin/modification-categorie:
  controller: Category
  action: updateCategory

/admin/suppression-categorie:
  controller : Category
  action: deleteCategory

/admin/nouveau-magasin:
  controller: Shop
  action: newShop


/admin/pages:
  controller: Pages
  action: pages


/admin/publisher:
  controller: Publisher
  action: publisher


/admin/check-review:
  controller: Reviews
  action: checkReviews


/admin/nouveau-role:
  controller: Role
  action: newRole

/admin/role:
  controller: Role
  action: showAll

/admin/modification-role:
  controller: Role
  action: updateRole

/admin/suppression-role:
  controller: Role
  action: deleteRole

/admin/info-reviews:
  controller: Reviews
  action: showProducts

/admin/del-review:
  controller: Reviews
  action: deleteReviews

/admin/show-reviews-from-products:
  controller: Reviews
  action: showReviewsFromProducts

/admin/orders:
  controller: Orders
  action: showOrders

/admin/info-order:
  controller: Orders
  action: infoOrder

/admin/ajout-client:
  controller: User
  action: newClient

/admin/liste-client:
  controller: User
  action: displayClient

/admin/modification-client:
  controller: User
  action: updateClient

/admin/suppression-client:
  controller: User
  action: deleteClient

/admin/detail-magasin:
  controller : Shop
  action : detailShop

/inscription:
  controller : User
  action: register

/mot-de-passe-oublie:
  controller : Security
  action : pwdPerdu

/recuperation-mot-de-passe:
  controller : Security
  action : recuperationpwd

/admin/delete-shop:
  controller: Shop
  action: deleteShop

/confirmation-inscription:
  controller: Security
  action: confirmedRegister

/admin/liste-utilisateurs:
  controller: User
  action: displayUsers

/admin/ajout-utilisateur:
  controller: User
  action: addUsers

/admin/suppression-utilisateur:
  controller: User
  action: deleteUser

/admin/modification-utilisateur:
  controller: User
  action: updateUser

/admin/utilisateur-changement-mdp:
  controller: User
  action : changeUserPwd

/admin/attribut:
  controller : Attribute
  action : attribute

/admin/valeurs-attribut:
  controller: Attribute
  action: termsAttribute

/admin/modification-attribut:
  controller: Attribute
  action: updateAttribute

/admin/suppression-attribut:
  controller: Attribute
  action : deleteAttribute

/admin/suppression-terme:
  controller: Attribute
  action : deleteTerm

/admin/ajout-produit:
  controller: Product
  action : addProduct

/admin/valeurs-attribut-ajax:
  controller : Product
  action : getValuesAttribute

/admin/creer-produit-ajax:
  controller : Product
  action : createProduct

/admin/liste-produits:
  controller: Product
  action: showProducts

/admin/information-produit:
  controller: Product
  action: infoProducts

/admin/del-produit-term:
  controller: Product
  action: deleteProduct

/admin/modification-produit:
  controller: Product
  action: updateProductForm

/admin/update-product-ajax:
  controller : Product
  action : updateProductAjax

/admin/update-var:
  controller: Product
  action: updateVar

/admin/update-p:
  controller: Product
  action: update

/admin/add-product-wv:
  controller: Product
  action: addProductWV

/admin/del-product:
  controller: Product
  action: delProduct

/admin/publish-product:
  controller: Product
  action: publishProduct

/admin/depublish-product:
  controller: Product
  action: depublishProduct

/admin/del-picture-variante:
  controller: Product
  action: delPicture

/admin/delete-variantes:
  controller: Product
  action: delVariantes